### ISSUE TITLE
Rendering a mongo deployment with 2 portals results in a since connection object

### ISSUE THREAD

**Issue by spritko** [benjdewan/pachelbel#5]
I have a Mongo deployment in compose that contains 2 `portals`, the connection string int he compose dashboard looks like
```
mongodb://<username>:<password>@host_1:port,host_2:port/admin?ssl=true
```
and produces 
```
- mongodb_1:
    connections:
    - host: host_1
      password: pwd
      path: /admin
      scheme: mongodb
      username: user
    type: mongodb
```
Also looks like the port is missing in the connection object as well
